# Generated by Django 3.2.4 on 2021-06-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_user'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='product',
            field=models.ManyToManyField(through='users.Like', to='products.Product'),
        ),
    ]
