# Generated by Django 3.2.4 on 2021-06-09 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='product',
            new_name='like',
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_like', to='users.user'),
        ),
    ]
