# Generated by Django 3.2.4 on 2021-06-09 18:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipientinfo',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.recipientinfo'),
            preserve_default=False,
        ),
    ]
