# Generated by Django 3.2.4 on 2021-06-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210611_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected',
            field=models.BooleanField(default=True),
        ),
    ]
